### ISSUE TITLE
coloring highlighting is messed up in some cases

### ISSUE THREAD

**Issue by FloLey** [inmanta/vscode-inmanta#1014]
The color highlighting of string seems to be messed up.
For example :
```
s = "this is a string"
ss = 'this is also a string'
sss = """this is "still" a string"""
ssss = """Let's \"break" it"""
sssss = "aaaaaaaaaaaaaaaaaaah"
```
will be colored like this:
![image.png](https://images.zenhubusercontent.com/61a72a44b0dfd661a656b110/466d25c7-1061-477d-a19c-8648f0eb62fe)

**Comment by sanderr** [comment]
The vim highlight rules seem to be all right, so if vscode uses a similar regex system (really no clue anymore if it does) we can easily copy them.
