### ISSUE TITLE
Automated VScode Release

### ISSUE THREAD

**Issue by wouterdb** [inmanta/vscode-inmanta#20]
Investigate whether the `irt/ci/inmanta-tools/Jenkinsfile-pyp` can be used (see for example `pytest-inmanta/.ci-pyp.yml`) to release the server part of the extension. The job expects the python project to exist in the root of the repo, but it could be easily extended with another option in the yml file.

**Comment by andraskvr** [comment]
A `.vscodeignore` file should be added as well, to make sure nothing is included that might be needed for testing but not for the released package
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#.vscodeignore
