### ISSUE TITLE
Language server fails to download modules from Git

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/vscode-inmanta#267]
**Steps to reproduce:**

* Open a project and make sure the language server starts and compiles the project successfully
* Add an additional import statement to the project, that would cause a new module to be downloaded into the download path of the project.
* When the language server recompiles the project, compilation will fail with the message `could not find module <module-name>`.

**Underlying root cause:**

* The language server is started with an empty list of environment variables (See: https://github.com/inmanta/vscode-inmanta/blob/65ad9290ba7e1253a7623036aa720a72f72c010d/src/extension.ts#L237).
* When the compiler venv is activated, the `PATH` environment variable is set (See: https://github.com/inmanta/inmanta-core/blob/6cb1ad4e557f9354ba38684a0752ee4addabeda2/src/inmanta/env.py#L363), but it only contains the bin directory of the compiler venv.
* The second time a module needs to be downloaded, the clone operation fails, because the `git` command cannot be found.

**Remark:** 

* It was confirmed that this issue exists for the pipeserver (on Linux). It should be confirmed whether this issue also exists for the tcpserver (on windows).

**Comment by bartv** [comment]
Does this still happen with the improvements in the last releases?

**Comment by arnaudsjs** [comment]
This issue doesn't happen anymore when using the latest version of the extension/compiler, because the latest compiler doesn't activate a compiler venv anymore.

**Comment by bartv** [comment]
I will close it then.
