### ISSUE TITLE
The python extension no longer shows the venv selection box by default

### ISSUE THREAD

**Issue by wouterdb** [inmanta/vscode-inmanta#545]
We rely on this box to select our own venv, so this is a bit annoying.

We have to figure out if we can get it back by default.

**Comment by FloLey** [comment]
https://github.com/microsoft/vscode-python/issues/19089

**Comment by sanderr** [comment]
Seems to be resolved on their side: https://github.com/microsoft/vscode-python/issues/19089#issuecomment-1194653775.

**Comment by FloLey** [comment]
https://github.com/microsoft/vscode-python/issues/20659
