### ISSUE TITLE
Language server does not start on windows

### ISSUE THREAD

**Issue by bartv** [inmanta/vscode-inmanta#63]
With a full updated vscode and latest extension when I open a new project with only a main.cf. The language server should start with opening the main.cf

I get the following:

![2020-11-13_11-16.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/6136c991-8b21-47fd-900d-31bdac7cbbc7)
![2020-11-13_11-15.png](https://images.zenhubusercontent.com/5a7c15184b5806bc2bc616c7/d2a50762-6628-4038-9534-2ada1db7b5c4)

**Comment by wouterdb** [comment]
this is probably the ioloop on py3.6

**Comment by kazaamjt** [comment]
@bartv using  both python 36 and 37 on windows, I was unable to reproduce this. How did you install python 36?

**Comment by bartv** [comment]
It is the python on my windows that installed there x time ago. I do not remember. I will install a fresh version

**Comment by bartv** [comment]
I updated python to the latest version (3.9 with `choco upgrade python`). I get a number of error messages, I was only able to find this in the logs:

```
[2020-11-17 12:14:42.962] [renderer1] [error] spawn c:\Users\Bart\AppData\Roaming\Code\User\globalStorage\inmanta.inmanta\.env\Scripts\python.exe ENOENT: Error: spawn c:\Users\Bart\AppData\Roaming\Code\User\globalStorage\inmanta.inmanta\.env\Scripts\python.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by kazaamjt** [comment]
@bartv that's probably the same issue I had https://github.com/inmanta/vscode-inmanta/issues/66
I'll see if I can reproduce this issue with a choco install of python 36.

**Comment by bartv** [comment]
When I create the env myself it seems to work:

```cmd
cd c:\Users\Bart\AppData\Roaming\Code\User\globalStorage\
mkdir inmanta.inmanta
python -m vevn .env
.env/Scripts/pip install inmantals
```

The last step fails because of asyncpg build

**Comment by kazaamjt** [comment]
yeah, as I said,t aht's a different issue and I created a ticket for it.
I tried to reproduce this with python 3.6 installed using choco, but still no dice.
