### ISSUE TITLE
VScode Extension fails to create venv on windows

### ISSUE THREAD

**Issue by kazaamjt** [inmanta/vscode-inmanta#66]
The extension, when started, fails to create a virtual environment.

**Comment by kazaamjt** [comment]
![image](https://user-images.githubusercontent.com/16069086/99248799-5624c880-2809-11eb-80e5-1366207bdd24.png)

**Comment by kazaamjt** [comment]
I believe this is due to the command being used is `python3` which is not available on my windows installation. (I used the official windows installers provided by https://www.python.org.

When I try to execute the `python3` command, the exitcode is also 9009:

```Powershell
PS D:\Projects\inmanta> Python3
PS D:\Projects\inmanta> $LASTEXITCODE
9009
```

**Comment by sanderr** [comment]
I believe this is no longer relevant because the vscode extension doesn't create venvs anymore.
