### ISSUE TITLE
Enable flake8 style checking on inmantals

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/vscode-inmanta#84]
This ticket is about the inmanta language server located in the `server` directory. The language server code should be style checked according to pep8, with behavior similar to that in our other repos. The `inmanta-core` repo can be used as an example for most steps.
- [ ] Update `setup.cfg` with `flake8` config.
- [ ] Update `.ci/Jenkinsfile-tests` with a style checking stage that runs `flake8` against `src` and `tests`.
- [ ] Add `Makefile` with `pep8` and `format` targets.
- [ ] Run `make format` to make all existing code comply with the enforced style.

**Comment by musaib072** [comment]
what i have to do please provide steps to do

**Comment by sanderr** [comment]
I've updated the ticket with a more detailed description of what needs to be done. If you want to work on this you can just open a pull request against master with the required changes and ask for my review. I'll make sure to add any other required reviewers.
