### ISSUE TITLE
Allow working on modules

### ISSUE THREAD

**Issue by wouterdb** [inmanta/vscode-inmanta#891]
- When a module is opened in vscode, detect this and create a project somewhere to be able to load all files of the module.
(cfr pytest-inmanta)
- only look at root dir
- Add options to set the repos to pull from in the configuration

**Comment by bartv** [comment]
This will not work for modules like connect because you might not have access to all dependencies. An option to handle this, is using something like python entrypoints to indicate which modules you want to load.

**Comment by wouterdb** [comment]
Good remark, we could load the _init and all open files and provide a config in vscode to override?

**Comment by bartv** [comment]
I think it is also import to still make things work when one import does not exist. For example vscode keeps on working even if an import does not exist. This is something we should do in the language server as well

[Screencast from 2022-12-21 17-08-50.webm](https://user-images.githubusercontent.com/10819/208950464-b06c786c-5f51-4824-aedc-cb0a5a8792b9.webm)
