### ISSUE TITLE
Support workspaces

### ISSUE THREAD

**Issue by wouterdb** [inmanta/vscode-inmanta#892]
Workspaces can have multiple root folders

Make sure this it is supported to have multiple projects/modules in one workspace

**Comment by sanderr** [comment]
This may be relevant: https://github.com/Microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#language-client--language-server

This applies to us: "If your extension is making use of the (now deprecated) workspace.rootPath property to work on the currently opened folder, then you are affected. See the section 'Eliminating workspace.rootPath below'."
