### ISSUE TITLE
Docstring on hover and pop-up for constructor/plugin definition

### ISSUE THREAD

**Issue by FloLey** [inmanta/vscode-inmanta#993]
- support hovering an entity to view its docstring: example on [slack](https://inmanta.slack.com/archives/CKRF0C8R3/p1677588281250569?thread_ts=1677249358.692579&cid=CKRF0C8R3)

- support a pop-up for a constructor/plugin definition when calling it: example on [slack](https://inmanta.slack.com/archives/CKRF0C8R3/p1677588281250569?thread_ts=1677249358.692579&cid=CKRF0C8R3)

**Comment by sanderr** [comment]
While this is not necessarily a stability improvement and therefore indeed part of the second epic, it sounds like an easy win to me. Let's try to implement it now, timeboxed to approximately 2 hours. The assumption is that all the logic is there and we just need to implement the vscode entrypoint for it.
